import Head from 'next/head';
// import {
//   Container, Typography, Card, CardContent, Grid
// } from '@material-ui/core';
import Hero1 from '../components/templates/heroes/hero1/Hero1';

// const styles = {};
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero1 />
      <main />
    </div>
  );
}
