import Head from 'next/head';
import { Button } from '@material-ui/core';
import Hero1 from '../components/templates/heroes/hero1/Hero1';

// const styles = {};
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero1
        title={(
          <>
            <span className="text-secondaryMain">Next.JS</span>
            <span> Template</span>
          </>
        )}
        subtitle="A template to create the website you dreamed of!"
        cta={(
          <Button variant="contained" color="primary" size="large">
            Tell me more
          </Button>
        )}
        contactMe
      />
      <main />
    </div>
  );
}
